### PR TITLE
Provision for TungstenFabric Labels

### PR DESCRIPTION
**Pull request by Prabhjot-Sethi**
Adding new environment variables, to provision TungstenFabric
labels in container images

### CODE REVIEW

**Comment by Andrey-mp** [comment]
Hi Prabhjot,
please note that new TF's zuul doesn't use this file - it creates own here https://github.com/progmaticlab/contrail-zuul-jobs/blob/master/roles/contrail-build-containers-devenv/templates/common.env.j2

**Comment by Prabhjot-Sethi** [comment]
@Andrey-mp, yes we can address the same there as well

**Comment by Prabhjot-Sethi** [comment]
Hi @Andrey-mp
Looks like gerrit for https://github.com/progmaticlab/contrail-zuul-jobs/ is setup but not being used so i have created a pull request for that as well, Please review https://github.com/progmaticlab/contrail-zuul-jobs/pull/1

**Comment by Andrey-mp** [comment]
Done. progmaticlab/contrail-zuul-jobs is a temporary place. this repo is used in new zuul for TF - http://zuul.sytes.net:8080/ 22.08.2019, 09:43, "Prabhjot Singh Sethi" <notifications@github.com>:Hi @Andrey-mpLooks like gerrit for https://github.com/progmaticlab/contrail-zuul-jobs/ is setup but not being used so i have created a pull request for that as well, Please review progmaticlab/contrail-zuul-jobs#1—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
