### PR TITLE
Changing from Docker to Docker CE

### PR DESCRIPTION
**Pull request by pujita96**
It fails to start lighttpd and the following error appears:
  echo 'ERROR: failed to obtain IP of local RPM repository'
ERROR: failed to obtain IP of local RPM repository
  docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS                    NAMES
c9eac7fc8bb4        registry:2          "/entrypoint.sh /e..."   31 seconds ago      Up 30 seconds                 0.0.0.0:6666->5000/tcp   tf-dev-env-registry
3baf55a977ec        sebp/lighttpd       "start.sh"               36 seconds ago      Exited (255) 35 seconds ago                            tf-dev-env-rpm-repo
  docker logs tf-dev-env-rpm-repo
chmod: /dev/pts/0: No such file or directory
2019-08-14 06:45:50: (server.c.748) opening errorlog '/dev/pts/0' failed: Permission denied
2019-08-14 06:45:50: (server.c.1518) Opening errorlog failed. Going down.
  exit 1

### CODE REVIEW

**Comment by Andrey-mp** [comment]
it would be good to change Ubuntu's version also then.

**Comment by Andrey-mp** [comment]
@pujita96 are you planning to change doc for ubuntu?

**Comment by Andrey-mp** [comment]
there is another solution is present also. you can use another version of lighttd container. 
sebp/lighttpd -> m4rcu5/lighttpd
But I agree that latest docker is better.

**Comment by pujita96** [comment]
@Andrey-mp We are just trying to fix the README based on what is already in use in startup.sh file.
For Ubuntu: https://github.com/tungstenfabric/tf-dev-env/blob/master/startup.sh#L93
For CentOS: https://github.com/tungstenfabric/tf-dev-env/blob/master/startup.sh#L71
We are looking to change docker to docker-ce in README document for CentOS. This change just ensures the document helps setting up correct dev-env. 
The docker.io works for ubuntu therefore there is no change required, we are addressing the change only for CentOS.

**Comment by Andrey-mp** [comment]
got it.

**Pull request merged**
